// Generated inputs keep the independently built worker on the canonical
// server guard and editorial context. Run before build, test and local start.
import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../', import.meta.url);
const repo = new URL('../', root);
const guard = readFileSync(new URL('src/utils/ssrf.ts', repo), 'utf8');
writeFileSync(new URL('src/ssrf.ts', root), '// Generated by scripts/prepare.mjs; edit src/utils/ssrf.ts at repo root.\n' + guard);
const files = ['relational-intelligence-protocol.md', 'gatherer.md'];
const context = files.map(name => readFileSync(new URL('claude/skills/' + name, repo), 'utf8')).join('\n\n');
writeFileSync(new URL('src/editorial-context.ts', root), '// Generated by scripts/prepare.mjs.\nexport const EDITORIAL_CONTEXT = ' + JSON.stringify(context) + ';\n');
