#!/usr/bin/env python3
"""gen_stats.py — the SINGLE SOURCE OF TRUTH for canon counts.

Reads the committed canon (`seed/*.json`) and, if present, the baked
`adai.db` (for auto-derived edge counts that live only in the DB, not the
JSON), and writes `seed/STATS.md` — one compact, regenerable, git-diffable
table set. Every other doc should LINK here instead of repeating numbers.

This exists because counts were being hand-copied into ~6 markdown files and
drifting. Numbers belong in one generated place; prose describes shape.

Run:
    python3 seed/_build/gen_stats.py            # writes seed/STATS.md
    python3 seed/_build/gen_stats.py --check     # exit 1 if STATS.md is stale
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SEED = REPO / "seed"
STATS = SEED / "STATS.md"
DB = REPO / "adai.db"


def _load(name: str) -> list:
    p = SEED / name
    return json.loads(p.read_text()) if p.exists() else []


def _curated_edge_counts(edges: list) -> Counter:
    c: Counter = Counter()
    for e in edges:
        # canon edges.json is all-curated and all-live (no valid_until set)
        c[e["edge_type"]] += 1
    return c


def _derived_from_db() -> tuple[Counter, int] | None:
    """Auto-derived edge counts live only in the baked DB, not the JSON."""
    if not DB.exists():
        return None
    try:
        db = sqlite3.connect(str(DB))
        rows = db.execute(
            "SELECT edge_type, count(*) FROM edges "
            "WHERE valid_until IS NULL AND created_by='embedding-multimodal-v1' "
            "GROUP BY edge_type"
        ).fetchall()
        emb = db.execute(
            "SELECT count(*) FROM node_embeddings WHERE kind='identity'"
        ).fetchone()
        db.close()
    except sqlite3.Error:
        return None
    c = Counter({t: n for t, n in rows})
    return c, (emb[0] if emb else 0)


def render() -> str:
    nodes = _load("nodes.json")
    edges = _load("edges.json")
    signals = _load("signals.json")
    contributors = _load("contributors.json")
    aliases = _load("aliases.json")

    nbt = Counter(n["type"] for n in nodes)
    ebt = _curated_edge_counts(edges)
    derived = _derived_from_db()

    L: list[str] = []
    L.append("# Seed Canon — counts (generated)")
    L.append("")
    L.append("> **Do not hand-edit.** Generated by `seed/_build/gen_stats.py`")
    L.append("> from the committed canon (`seed/*.json`) + the baked `adai.db`.")
    L.append("> This is the single source of truth for counts — every other doc")
    L.append("> describes *shape* and links here. Regenerate after any canon")
    L.append("> change: `python3 seed/_build/gen_stats.py`. Live counts on a")
    L.append("> running server: `GET /api/stats`.")
    L.append("")
    L.append(f"**Totals:** {len(nodes):,} nodes · {len(edges):,} curated edges · "
             f"{len(signals)} signals · {len(contributors)} contributor(s) · "
             f"{len(aliases):,} aliases")
    L.append("")
    L.append("## Nodes by type")
    L.append("")
    L.append("| type | count |")
    L.append("|---|--:|")
    for t, n in sorted(nbt.items(), key=lambda kv: -kv[1]):
        L.append(f"| {t} | {n:,} |")
    L.append("")
    L.append("## Curated edges by type")
    L.append("")
    L.append("| edge_type | count |")
    L.append("|---|--:|")
    for t, n in sorted(ebt.items(), key=lambda kv: -kv[1]):
        L.append(f"| {t} | {n:,} |")
    L.append("")
    L.append("## Auto-derived edges (embedding pipeline)")
    L.append("")
    if derived is None:
        L.append("_No `adai.db` present — run `npm run seed:consolidated`, then "
                 "regenerate. These also show live at `GET /api/stats`._")
    else:
        dc, emb = derived
        L.append(f"From the baked `adai.db` (`created_by='embedding-multimodal-v1'`), "
                 f"over {emb:,} node embeddings:")
        L.append("")
        L.append("| edge_type | count |")
        L.append("|---|--:|")
        for t, n in sorted(dc.items(), key=lambda kv: -kv[1]):
            L.append(f"| {t} | {n:,} |")
        L.append("")
        L.append("_Refreshed on every `npm run embed:derive` (daily on Fly). "
                 "These are NOT in the committed JSON — they're recomputed from "
                 "vectors._")
    L.append("")
    L.append("## Signals (provenance batches)")
    L.append("")
    L.append("| signal_id | source |")
    L.append("|---|---|")
    for s in signals:
        L.append(f"| `{s['id']}` | {s.get('source_url','')} |")
    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if seed/STATS.md is out of date (CI guard)")
    args = ap.parse_args()

    content = render()
    if args.check:
        current = STATS.read_text() if STATS.exists() else ""
        if current.strip() != content.strip():
            print("seed/STATS.md is STALE — run: python3 seed/_build/gen_stats.py",
                  file=sys.stderr)
            return 1
        print("seed/STATS.md is up to date.")
        return 0

    STATS.write_text(content + "\n")
    print(f"wrote {STATS.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
